---
name: Minify

on:
  push:
    paths:
    - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Python 3.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python minify.py

      - name: Print changelog
        run: echo "test2"

