---
name: Minify

on:
  push:
    paths:
    - 'data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          pip3 install -r requirements.txt 
          python3 minify.py
      
      - name: Print changelog
        run: echo "test2"

